In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from sklearn.preprocessing import StandardScaler

In [2]:
%%time
df=pd.read_csv("Data/NY data no missing values.csv")

Wall time: 4.51 s

In [3]:
df.head()

,FULLVAL,AVLAND,AVTOT,LTFRONT,LTDEPTH,BLDFRONT,BLDDEPTH,ZIP,STORIES,RECORD,B,BLOCK,LOT,TAXCLASS
0,21400000.0,4225500.0,9630000.0,500.0,1046.0,152.0,207.0,10004.0,7.0,1,1,1,101,4
1,193800000.0,14310000.0,87210000.0,27.0,207.0,152.0,207.0,10004.0,7.0,2,1,1,201,4
2,104686000.0,39008700.0,47108700.0,709.0,564.0,709.0,564.0,10004.0,3.0,3,1,2,1,4
3,39200000.0,15255000.0,17640000.0,793.0,551.0,85.0,551.0,10004.0,2.0,4,1,2,23,4
4,272300000.0,121050000.0,122535000.0,323.0,1260.0,89.0,57.0,10004.0,1.0,5,1,3,1,4

In [4]:
df['S1']=df['LTFRONT']*df['LTDEPTH']
df['S2']=df['BLDFRONT']*df['BLDDEPTH']
df['S3']=df['S2']*df['STORIES']

In [5]:
df['R1']=df['FULLVAL']/df['S1']
df['R2']=df['FULLVAL']/df['S2']
df['R3']=df['FULLVAL']/df['S3']
df['R4']=df['AVLAND']/df['S1']
df['R5']=df['AVLAND']/df['S2']
df['R6']=df['AVLAND']/df['S3']
df['R7']=df['AVTOT']/df['S1']
df['R8']=df['AVTOT']/df['S2']
df['R9']=df['AVTOT']/df['S3']

In [6]:
df['ZIP5']=df['ZIP'].apply(str).str.slice(0,5)

In [7]:
df['ZIP3']=df['ZIP5'].str.slice(0,3)

In [8]:
zip5_group=df.groupby(['ZIP5'])['R1','R2','R3','R4','R5','R6','R7','R8','R9'].mean().reset_index()
zip5_group=zip5_group.add_prefix('zip5_')

In [9]:
zip3_group=df.groupby(['ZIP3'])['R1','R2','R3','R4','R5','R6','R7','R8','R9'].mean().reset_index()
zip3_group=zip3_group.add_prefix('zip3_')

In [10]:
tax_group=df.groupby(['TAXCLASS'])['R1','R2','R3','R4','R5','R6','R7','R8','R9'].mean().reset_index()
tax_group=tax_group.add_prefix('tax_')
tax_group.head()

,tax_TAXCLASS,tax_R1,tax_R2,tax_R3,tax_R4,tax_R5,tax_R6,tax_R7,tax_R8,tax_R9
0,1,230.140473,706.030281,341.891633,5.785087,18.279705,9.028937,9.735292,30.819130,15.134036
1,1A,190.565104,420.937309,304.953234,1.191052,2.863045,1.913394,7.992647,18.260507,12.856425
2,1B,100.914839,140.428409,35.107312,1.931551,3.688426,0.922115,1.932268,3.689130,0.922290
3,1C,331.742081,613.990331,227.188999,3.540406,6.432038,2.365525,12.445702,22.868213,8.154554
4,1D,103.687211,26709.078993,26435.081690,2.556414,774.552451,768.586899,4.622933,1311.888686,1300.929482

In [11]:
b_group=df.groupby(['B'])['R1','R2','R3','R4','R5','R6','R7','R8','R9'].mean().reset_index()
b_group=b_group.add_prefix('b_')

In [12]:
df['R1_avg']=df.R1.mean()
df['R2_avg']=df.R2.mean()
df['R3_avg']=df.R3.mean()
df['R4_avg']=df.R4.mean()
df['R5_avg']=df.R5.mean()
df['R6_avg']=df.R6.mean()
df['R7_avg']=df.R7.mean()
df['R8_avg']=df.R8.mean()
df['R9_avg']=df.R9.mean()

In [13]:
df=pd.merge(df,zip5_group,left_on='ZIP5',right_on='zip5_ZIP5',how='left')
df=pd.merge(df,zip3_group,left_on='ZIP3',right_on='zip3_ZIP3',how='left')
df=pd.merge(df,tax_group,left_on='TAXCLASS',right_on='tax_TAXCLASS',how='left')
df=pd.merge(df,b_group,left_on='B',right_on='b_B',how='left')

In [14]:
df.columns

Index(['FULLVAL', 'AVLAND', 'AVTOT', 'LTFRONT', 'LTDEPTH', 'BLDFRONT',
       'BLDDEPTH', 'ZIP', 'STORIES', 'RECORD', 'B', 'BLOCK', 'LOT', 'TAXCLASS',
       'S1', 'S2', 'S3', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9',
       'ZIP5', 'ZIP3', 'R1_avg', 'R2_avg', 'R3_avg', 'R4_avg', 'R5_avg',
       'R6_avg', 'R7_avg', 'R8_avg', 'R9_avg', 'zip5_ZIP5', 'zip5_R1',
       'zip5_R2', 'zip5_R3', 'zip5_R4', 'zip5_R5', 'zip5_R6', 'zip5_R7',
       'zip5_R8', 'zip5_R9', 'zip3_ZIP3', 'zip3_R1', 'zip3_R2', 'zip3_R3',
       'zip3_R4', 'zip3_R5', 'zip3_R6', 'zip3_R7', 'zip3_R8', 'zip3_R9',
       'tax_TAXCLASS', 'tax_R1', 'tax_R2', 'tax_R3', 'tax_R4', 'tax_R5',
       'tax_R6', 'tax_R7', 'tax_R8', 'tax_R9', 'b_B', 'b_R1', 'b_R2', 'b_R3',
       'b_R4', 'b_R5', 'b_R6', 'b_R7', 'b_R8', 'b_R9'],
      dtype='object')

In [15]:
df['R1_zip5_scaled']=df['R1']/df['zip5_R1']

In [16]:
org=['R1','R2','R3','R4','R5','R6','R7','R8','R9']
zip5=['zip5_R1', 'zip5_R2', 'zip5_R3', 'zip5_R4','zip5_R5', 'zip5_R6', 'zip5_R7', 'zip5_R8', 'zip5_R9']
d=['R1_zip5_scaled','R2_zip5_scaled','R3_zip5_scaled','R4_zip5_scaled','R5_zip5_scaled','R6_zip5_scaled','R7_zip5_scaled','R8_zip5_scaled','R9_zip5_scaled']

for i in range(len(org)):
    df[d[i]]=df[org[i]]/df[zip5[i]]

In [17]:
df.columns

Index(['FULLVAL', 'AVLAND', 'AVTOT', 'LTFRONT', 'LTDEPTH', 'BLDFRONT',
       'BLDDEPTH', 'ZIP', 'STORIES', 'RECORD', 'B', 'BLOCK', 'LOT', 'TAXCLASS',
       'S1', 'S2', 'S3', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9',
       'ZIP5', 'ZIP3', 'R1_avg', 'R2_avg', 'R3_avg', 'R4_avg', 'R5_avg',
       'R6_avg', 'R7_avg', 'R8_avg', 'R9_avg', 'zip5_ZIP5', 'zip5_R1',
       'zip5_R2', 'zip5_R3', 'zip5_R4', 'zip5_R5', 'zip5_R6', 'zip5_R7',
       'zip5_R8', 'zip5_R9', 'zip3_ZIP3', 'zip3_R1', 'zip3_R2', 'zip3_R3',
       'zip3_R4', 'zip3_R5', 'zip3_R6', 'zip3_R7', 'zip3_R8', 'zip3_R9',
       'tax_TAXCLASS', 'tax_R1', 'tax_R2', 'tax_R3', 'tax_R4', 'tax_R5',
       'tax_R6', 'tax_R7', 'tax_R8', 'tax_R9', 'b_B', 'b_R1', 'b_R2', 'b_R3',
       'b_R4', 'b_R5', 'b_R6', 'b_R7', 'b_R8', 'b_R9', 'R1_zip5_scaled',
       'R2_zip5_scaled', 'R3_zip5_scaled', 'R4_zip5_scaled', 'R5_zip5_scaled',
       'R6_zip5_scaled', 'R7_zip5_scaled', 'R8_zip5_scaled', 'R9_zip5_scaled'],
      dtype='object')

In [18]:
to_add='zip3'

org=['R1','R2','R3','R4','R5','R6','R7','R8','R9']
zip3=[]
d=[]
for elem in org:
    elem=to_add+'_'+elem
    zip3.append(elem)

for elem in org:
    elem=elem+to_add+'_scaled'
    d.append(elem)

for i in range(len(org)):
    df[d[i]]=df[org[i]]/df[zip3[i]]

In [19]:
df.columns

Index(['FULLVAL', 'AVLAND', 'AVTOT', 'LTFRONT', 'LTDEPTH', 'BLDFRONT',
       'BLDDEPTH', 'ZIP', 'STORIES', 'RECORD', 'B', 'BLOCK', 'LOT', 'TAXCLASS',
       'S1', 'S2', 'S3', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9',
       'ZIP5', 'ZIP3', 'R1_avg', 'R2_avg', 'R3_avg', 'R4_avg', 'R5_avg',
       'R6_avg', 'R7_avg', 'R8_avg', 'R9_avg', 'zip5_ZIP5', 'zip5_R1',
       'zip5_R2', 'zip5_R3', 'zip5_R4', 'zip5_R5', 'zip5_R6', 'zip5_R7',
       'zip5_R8', 'zip5_R9', 'zip3_ZIP3', 'zip3_R1', 'zip3_R2', 'zip3_R3',
       'zip3_R4', 'zip3_R5', 'zip3_R6', 'zip3_R7', 'zip3_R8', 'zip3_R9',
       'tax_TAXCLASS', 'tax_R1', 'tax_R2', 'tax_R3', 'tax_R4', 'tax_R5',
       'tax_R6', 'tax_R7', 'tax_R8', 'tax_R9', 'b_B', 'b_R1', 'b_R2', 'b_R3',
       'b_R4', 'b_R5', 'b_R6', 'b_R7', 'b_R8', 'b_R9', 'R1_zip5_scaled',
       'R2_zip5_scaled', 'R3_zip5_scaled', 'R4_zip5_scaled', 'R5_zip5_scaled',
       'R6_zip5_scaled', 'R7_zip5_scaled', 'R8_zip5_scaled', 'R9_zip5_scaled',
       'R1zip3_scaled', 'R2zip3_scaled', 'R3zip3_scaled', 'R4zip3_scaled',
       'R5zip3_scaled', 'R6zip3_scaled', 'R7zip3_scaled', 'R8zip3_scaled',
       'R9zip3_scaled'],
      dtype='object')

In [20]:
to_add='b'

org=['R1','R2','R3','R4','R5','R6','R7','R8','R9']
b=[]
d=[]
for elem in org:
    elem=to_add+'_'+elem
    b.append(elem)

for elem in org:
    elem=elem+to_add+'_scaled'
    d.append(elem)

for i in range(len(org)):
    df[d[i]]=df[org[i]]/df[b[i]]

In [21]:
df.columns

Index(['FULLVAL', 'AVLAND', 'AVTOT', 'LTFRONT', 'LTDEPTH', 'BLDFRONT',
       'BLDDEPTH', 'ZIP', 'STORIES', 'RECORD',
       ...
       'R9zip3_scaled', 'R1b_scaled', 'R2b_scaled', 'R3b_scaled', 'R4b_scaled',
       'R5b_scaled', 'R6b_scaled', 'R7b_scaled', 'R8b_scaled', 'R9b_scaled'],
      dtype='object', length=104)

In [22]:
to_add='tax'

org=['R1','R2','R3','R4','R5','R6','R7','R8','R9']
tax=[]
d=[]
for elem in org:
    elem=to_add+'_'+elem
    tax.append(elem)

for elem in org:
    elem=elem+to_add+'_scaled'
    d.append(elem)

for i in range(len(org)):
    df[d[i]]=df[org[i]]/df[tax[i]]

In [23]:
org=['R1','R2','R3','R4','R5','R6','R7','R8','R9']
overall=[]
d=[]
for elem in org:
    elem=elem+'_avg'
    overall.append(elem)

for elem in org:
    elem=elem+'overall'+'_scaled'
    d.append(elem)

for i in range(len(org)):
    df[d[i]]=df[org[i]]/df[overall[i]]

In [24]:
to_drop=[]
cols=[zip5_group,zip3_group,tax_group,b_group]

for dfs in cols:
    for i in range(10):
        to_drop.append(dfs.columns[i])

for i in range(9):
    to_drop.append(overall[i])
# to_drop.append(zip5_group.columns,zip3_group.columns)
# to_drop.append(zip3_group.columns)
# to_drop.append(tax_group.columns)
# to_drop.append(b_group.columns)
# to_drop.append(overall)

In [25]:
df_final=df.drop(to_drop,axis=1)

In [26]:
df_target=df.loc[:,['R1_zip5_scaled', 'R2_zip5_scaled', 'R3_zip5_scaled', 'R4_zip5_scaled',
       'R5_zip5_scaled', 'R6_zip5_scaled', 'R7_zip5_scaled', 'R8_zip5_scaled',
       'R9_zip5_scaled', 'R1zip3_scaled', 'R2zip3_scaled', 'R3zip3_scaled',
       'R4zip3_scaled', 'R5zip3_scaled', 'R6zip3_scaled', 'R7zip3_scaled',
       'R8zip3_scaled', 'R9zip3_scaled', 'R1b_scaled', 'R2b_scaled',
       'R3b_scaled', 'R4b_scaled', 'R5b_scaled', 'R6b_scaled', 'R7b_scaled',
       'R8b_scaled', 'R9b_scaled', 'R1tax_scaled', 'R2tax_scaled',
       'R3tax_scaled', 'R4tax_scaled', 'R5tax_scaled', 'R6tax_scaled',
       'R7tax_scaled', 'R8tax_scaled', 'R9tax_scaled', 'R1overall_scaled',
       'R2overall_scaled', 'R3overall_scaled', 'R4overall_scaled',
       'R5overall_scaled', 'R6overall_scaled', 'R7overall_scaled',
       'R8overall_scaled', 'R9overall_scaled']]

In [27]:
df_target.rename(columns = {'R1_zip5_scaled':'FV/LotArea_Zip5'}, inplace = True) #r1_zip5
df_target.rename(columns = {'R2_zip5_scaled':'FV/BldArea_Zip5'}, inplace = True) #r2_zip5
df_target.rename(columns = {'R3_zip5_scaled':'FV/BldVol_Zip5'}, inplace = True) #r3_zip5
df_target.rename(columns = {'R4_zip5_scaled':'AVL/LotArea_Zip5'}, inplace = True) #r4_zip5
df_target.rename(columns = {'R5_zip5_scaled':'AVL/BldArea_Zip5'}, inplace = True) #r5_zip5
df_target.rename(columns = {'R6_zip5_scaled':'AVL/BldVol_Zip5'}, inplace = True) #r6_zip5
df_target.rename(columns = {'R7_zip5_scaled':'AVT/LotArea_Zip5'}, inplace = True) #r7_zip5
df_target.rename(columns = {'R8_zip5_scaled':'AVT/BldArea_Zip5'}, inplace = True) #r8_zip5
df_target.rename(columns = {'R9_zip5_scaled':'AVT/BldVol_Zip5'}, inplace = True) #r9_zip5
 

df_target.rename(columns = {'R1zip3_scaled':'FV/LotArea_Zip3'}, inplace = True) #r1_zip3
df_target.rename(columns = {'R2zip3_scaled':'FV/BldArea_Zip3'}, inplace = True) #r2_zip3
df_target.rename(columns = {'R3zip3_scaled':'FV/BldVol_Zip3'}, inplace = True) #r3_zip3
df_target.rename(columns = {'R4zip3_scaled':'AVL/LotArea_Zip3'}, inplace = True) #r4_zip3
df_target.rename(columns = {'R5zip3_scaled':'AVL/BldArea_Zip3'}, inplace = True) #r5_zip3
df_target.rename(columns = {'R6zip3_scaled':'AVL/BldVol_Zip3'}, inplace = True) #r6_zip3
df_target.rename(columns = {'R7zip3_scaled':'AVT/LotArea_Zip3'}, inplace = True) #r7_zip3
df_target.rename(columns = {'R8zip3_scaled':'AVT/BldArea_Zip3'}, inplace = True) #r8_zip3
df_target.rename(columns = {'R9zip3_scaled':'AVT/BldVol_Zip3'}, inplace = True) #r9_zip3
 

df_target.rename(columns = {'R1b_scaled':'FV/LotArea_Boro'}, inplace = True)
df_target.rename(columns = {'R2b_scaled':'FV/BldArea_Boro'}, inplace = True)
df_target.rename(columns = {'R3b_scaled':'FV/BldVol_Boro'}, inplace = True)
df_target.rename(columns = {'R4b_scaled':'AVL/LotArea_Boro'}, inplace = True)
df_target.rename(columns = {'R5b_scaled':'AVL/BldArea_Boro'}, inplace = True)
df_target.rename(columns = {'R6b_scaled':'AVL/BldVol_Boro'}, inplace = True)
df_target.rename(columns = {'R7b_scaled':'AVT/LotArea_Boro'}, inplace = True)
df_target.rename(columns = {'R8b_scaled':'AVT/BldArea_Boro'}, inplace = True)
df_target.rename(columns = {'R9b_scaled':'AVT/BldVol_Boro'}, inplace = True)

df_target.rename(columns = {'R1tax_scaled':'FV/LotArea_tax'}, inplace = True)
df_target.rename(columns = {'R2tax_scaled':'FV/BldArea_tax'}, inplace = True)
df_target.rename(columns = {'R3tax_scaled':'FV/BldVol_tax'}, inplace = True)
df_target.rename(columns = {'R4tax_scaled':'AVL/LotArea_tax'}, inplace = True)
df_target.rename(columns = {'R5tax_scaled':'AVL/BldArea_tax'}, inplace = True)
df_target.rename(columns = {'R6tax_scaled':'AVL/BldVol_tax'}, inplace = True)

df_target.rename(columns = {'R7tax_scaled':'AVT/LotArea_tax'}, inplace = True)
df_target.rename(columns = {'R8tax_scaled':'AVT/BldArea_tax'}, inplace = True)
df_target.rename(columns = {'R9tax_scaled':'AVT/BldVol_tax'}, inplace = True)
 
df_target.rename(columns = {'R1overall_scaled':'FV/LotArea'}, inplace = True)
df_target.rename(columns = {'R2overall_scaled':'FV/BldArea'}, inplace = True)
df_target.rename(columns = {'R3overall_scaled':'FV/BldVol'}, inplace = True)
df_target.rename(columns = {'R4overall_scaled':'AVL/LotArea'}, inplace = True)
df_target.rename(columns = {'R5overall_scaled':'AVL/BldArea'}, inplace = True)
df_target.rename(columns = {'R6overall_scaled':'AVL/BldVol'}, inplace = True)
df_target.rename(columns = {'R7overall_scaled':'AVT/LotArea'}, inplace = True)
df_target.rename(columns = {'R8overall_scaled':'AVT/BldArea'}, inplace = True)
df_target.rename(columns = {'R9overall_scaled':'AVT/BldVol'}, inplace = True)

In [28]:
df_target.shape

(1070994, 45)

In [29]:
for key in df_target.keys():
    ss = StandardScaler()
    df_target[key] = ss.fit_transform(df_target[key].values.reshape(-1, 1))

In [30]:
df_target['RECORD'] = df['RECORD']

In [31]:
df_target.head()

,FV/LotArea_Zip5,FV/BldArea_Zip5,FV/BldVol_Zip5,AVL/LotArea_Zip5,AVL/BldArea_Zip5,AVL/BldVol_Zip5,AVT/LotArea_Zip5,AVT/BldArea_Zip5,AVT/BldVol_Zip5,FV/LotArea_Zip3,FV/BldArea_Zip3,FV/BldVol_Zip3,AVL/LotArea_Zip3,AVL/BldArea_Zip3,AVL/BldVol_Zip3,AVT/LotArea_Zip3,AVT/BldArea_Zip3,AVT/BldVol_Zip3,FV/LotArea_Boro,FV/BldArea_Boro,FV/BldVol_Boro,AVL/LotArea_Boro,AVL/BldArea_Boro,AVL/BldVol_Boro,AVT/LotArea_Boro,AVT/BldArea_Boro,AVT/BldVol_Boro,FV/LotArea_tax,FV/BldArea_tax,FV/BldVol_tax,AVL/LotArea_tax,AVL/BldArea_tax,AVL/BldVol_tax,AVT/LotArea_tax,AVT/BldArea_tax,AVT/BldVol_tax,FV/LotArea,FV/BldArea,FV/BldVol,AVL/LotArea,AVL/BldArea,AVL/BldVol,AVT/LotArea,AVT/BldArea,AVT/BldVol,RECORD
0,-0.223270,0.062910,-0.027061,-0.068649,0.018660,-0.026038,-0.092380,0.037145,-0.012569,-0.133713,0.014156,-0.021329,-0.034928,0.012848,-0.002502,-0.073700,0.018156,0.003536,-0.132265,0.015071,-0.019376,-0.034788,0.012645,-0.001785,-0.073914,0.017854,0.004438,-0.148266,-0.002232,-0.008363,-0.106864,-0.005948,-0.005931,-0.124603,-0.004145,-0.008495,-0.160450,0.011333,-0.041557,-0.013114,0.032995,0.000575,-0.031650,0.061926,0.008842,1
1,25.744006,1.474659,0.498457,4.389035,0.175007,0.009973,11.814448,0.777774,0.281572,13.509351,0.763449,0.333716,3.077904,0.076133,0.021798,13.728172,0.313364,0.172571,13.770524,0.720969,0.336354,3.219611,0.072505,0.021770,14.330333,0.299387,0.177497,26.294119,0.314813,0.021485,7.962472,0.019552,-0.002845,22.090149,0.286127,0.020116,32.370894,0.657342,0.149074,14.678657,0.142083,0.028595,65.033747,0.705361,0.209202,2
2,-0.057665,-0.044878,-0.033706,0.087617,0.000736,-0.015552,-0.016444,-0.019402,-0.016289,-0.046705,-0.043053,-0.025819,0.074195,0.005593,0.004573,0.014320,-0.004384,0.001399,-0.043601,-0.038825,-0.023875,0.079297,0.005782,0.005074,0.017948,-0.003642,0.002250,0.020369,-0.026439,-0.008741,0.176011,-0.008872,-0.005032,0.017070,-0.026307,-0.008857,0.047017,-0.037991,-0.043967,0.501915,0.020488,0.008734,0.383300,0.012799,0.006309,3
3,-0.186684,0.103320,0.188669,-0.021784,0.112037,0.086960,-0.075604,0.058345,0.108178,-0.114491,0.035603,0.124420,-0.002201,0.050645,0.073748,-0.054255,0.026606,0.072926,-0.112677,0.035277,0.126654,-0.000572,0.048396,0.072127,-0.053620,0.025912,0.075480,-0.111011,0.006843,0.003890,-0.022027,0.009282,0.003752,-0.093305,0.004164,0.003250,-0.114616,0.029824,0.036699,0.141348,0.098147,0.088499,0.060021,0.080344,0.091092,4
4,0.247694,13.717502,35.944431,0.436719,11.593015,18.725809,0.123573,7.200589,20.121279,0.113729,7.261407,24.281395,0.317975,4.697873,12.651014,0.176622,2.873440,11.573940,0.119888,6.842591,24.330185,0.334164,4.444124,12.263723,0.187333,2.740873,11.850230,0.331315,3.064268,2.034736,0.807957,1.881827,1.600981,0.278302,2.803397,1.949880,0.429565,6.259609,13.007068,1.652495,8.108790,14.591445,1.148429,6.285300,13.723383,5

In [32]:
%%time
df_target.to_csv('Data/NY data features.csv', index = False)

Wall time: 5min 11s